-- Auto-generated from PZ script files by pz_script_parser.py
-- Reload with: python pz_script_parser.py --lua <script_file.txt> > weapon_scripts.lua

_pz_weapon_scripts["Base.Axe"] = {
    _displayName = "Axe",
    _hasHeadCondition = true,
    _hasSharpness = true,
    _headConditionMax = 13,
    _isRanged = false,
    _name = "Axe",
    baseSpeed = 1.0,
    conditionLowerChance = 35,
    conditionMax = 13,
    critDmgMultiplier = 5.0,
    criticalChance = 20.0,
    doorDamage = 35,
    knockdownMod = 2.0,
    maxDamage = 2.0,
    maxHitCount = 2,
    maxRange = 1.2,
    minDamage = 0.8,
    minRange = 0.61,
    pushBackMod = 0.3,
    treeDamage = 35,
}
_pz_weapon_scripts["Base.Pistol"] = {
    _displayName = "Pistol",
    _hasHeadCondition = false,
    _hasSharpness = false,
    _isRanged = true,
    _magazineType = "Base.9mmClip",
    _name = "Pistol",
    _reloadType = "handgun",
    aimingTime = 25,
    clipSize = 15,
    conditionLowerChance = 200,
    conditionMax = 10,
    critDmgMultiplier = 4.0,
    criticalChance = 20.0,
    doorDamage = 5,
    hitChance = 50,
    jamGunChance = 1,
    knockdownMod = 2.0,
    maxAmmo = 15,
    maxDamage = 1.0,
    maxHitCount = 1,
    maxRange = 15.0,
    minDamage = 0.6,
    minRange = 0.61,
    pushBackMod = 0.3,
    recoilDelay = 12,
    reloadTime = 30,
    soundGain = 1.5,
    soundRadius = 100,
}

